input.onButtonPressed(Button.A, function () {
    led.setBrightness(255)
    basic.showIcon(IconNames.Skull)
    led.setBrightness(43)
    basic.showIcon(IconNames.Skull)
    led.setBrightness(255)
    basic.showIcon(IconNames.Skull)
    led.setBrightness(43)
    basic.showIcon(IconNames.Skull)
    led.setBrightness(255)
    basic.showIcon(IconNames.Skull)
    led.setBrightness(43)
    basic.showIcon(IconNames.Skull)
    led.setBrightness(255)
    basic.showIcon(IconNames.Skull)
    led.setBrightness(43)
    basic.showIcon(IconNames.Skull)
    led.setBrightness(255)
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.Heart)
})
basic.showIcon(IconNames.Skull)
for (let index = 0; index < 4; index++) {
    music.playMelody("A F E F A F E F ", 120)
    music.playMelody("D G A G D A G C5 ", 120)
    music.playMelody("A F E F G F E F ", 120)
}
